### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by amen183** [xinario/catgan_pytorch#1]
iter_idx = 0
with open(os.path.join(opt.results_dir, opt.name, 'log.csv'), 'wb') as log:
    log_writer = csv.writer(log, delimiter=',')

    for epoch in range(opt.num_epochs):
        start_time = time.time()
        for batch_idx, (real, labels) in enumerate(dataloader):

**While i ran the program, errror occured.**

    for batch_idx, (real, labels) in enumerate(dataloader):

  File "D:\Program Files\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 451, in __iter__
    return _DataLoaderIter(self)

  File "D:\Program Files\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 239, in __init__
    w.start()

  File "D:\Program Files\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)

  File "D:\Program Files\Anaconda3\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "D:\Program Files\Anaconda3\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)

  File "D:\Program Files\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)

  File "D:\Program Files\Anaconda3\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)

BrokenPipeError: [Errno 32] Broken pipe

can you tell me how to solve this problem?

**Comment by xinario** [comment]
In the dataloader, you can try to set num_workers to 0 by "--workers 0"

**Comment by amen183** [comment]
> In the dataloader, you can try to set num_workers to 0 by "--workers 0"

**I have set it to be 0, however, another error appears.**
 File "D:\Program Files\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "D:\Program Files\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "G:/百度云同步盘/研究生活/期刊论文准备/程序/1.机器学习/6.catgan_pytorch-master/catgan_cifar10.py", line 232, in <module>
    D_real = netD(real)

  File "D:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "G:/百度云同步盘/研究生活/期刊论文准备/程序/1.机器学习/6.catgan_pytorch-master/catgan_cifar10.py", line 110, in forward
    output = self.main(input)

  File "D:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "D:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)

  File "D:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)

  File "D:\Program Files\Anaconda3\lib\site-packages\torch\nn\modules\conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)

RuntimeError: CUDNN_STATUS_ARCH_MISMATCH

**Did you face this problem?**

**Comment by amen183** [comment]
**maybe it 's because the gpu doen't support cudnn. However, when i use another computer, errors still occurs which are as follows**
 UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output = self.softmax(output)
Traceback (most recent call last):

  File "<ipython-input-1-fec776c96ece>", line 1, in <module>
    runfile('D:/6.catgan_pytorch-master/catgan_cifar10.py', wdir='D:/6.catgan_pytorch-master')

  File "D:\Programfiles\Anaconda3\envs\tensorflow\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "D:\Programfiles\Anaconda3\envs\tensorflow\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/6.catgan_pytorch-master/catgan_cifar10.py", line 235, in <module>
    entorpy2_real.backward(one, retain_graph=True)

  File "D:\Programfiles\Anaconda3\envs\tensorflow\lib\site-packages\torch\tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)

  File "D:\Programfiles\Anaconda3\envs\tensorflow\lib\site-packages\torch\autograd\__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag

RuntimeError: invalid gradient at index 0 - expected shape [] but got [1]

**Could you please tell me why and give me the codes that can be debugged correctly? Thanks a lot.**

**Comment by xinario** [comment]
Note that the code was only tested on ubuntu16.04 with pytorch v0.2. What I would suggest you do is making a clean install in a new environment and start from there.

**Comment by amen183** [comment]
> Note that the code was only tested on ubuntu16.04 with pytorch v0.2. What I would suggest you do is making a clean install in a new environment and start from there.

Thank you very much. I have reconfigure my environmnent. And the program can be ran correctly.
